version: '3.8'

services:
  # Redis服务
  redis:
    image: redis:7-alpine
    container_name: fishing-game-redis
    ports:
      - "6379:6379"
    networks:
      - fishing-network
    command: redis-server --save "" --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fishing-game-backend
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - fishing-network
    volumes:
      - ./backend/configs:/root/configs:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/fishing/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3

# 网络配置
networks:
  fishing-network:
    driver: bridge

# 数据卷配置已移除 - Redis不再使用持久化存储
